### ISSUE TITLE
README video broken

### ISSUE THREAD

**Issue by 1268** [lf-/clipper#11]
currently I see this URL:

https://github.com/lf-/clipper/blob/93770bfb87d3f58ec28b7b2af4e361066b9c8787/README.md?plain=1#L84

however it appears to be broken. running this command:

~~~
curl -L -i https://github.com/lf-/clipper/assets/6652840/47a07fdf-e73b-4a12-b15a-df4812a34c24
~~~

result:

~~~
HTTP/1.1 403 Forbidden
x-amz-request-id: YSX4SZ4Q3PEV2FRV
x-amz-id-2: Y7mZ3MCetP4pRH0XO7ebdwKaWNVbiy8arVKpkBrDu+xTrVgw4tEC+u5PTFWBTRMEymTmiaNZ/RA=
Content-Type: application/xml
Transfer-Encoding: chunked
Date: Tue, 25 Jul 2023 00:11:12 GMT
Server: AmazonS3

<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>YSX4SZ4Q3PEV2FRV</RequestId><HostId>Y7mZ3MCetP4pRH0XO7ebdwKaWNVbiy8arVKpkBrDu+xTrVgw4tEC+u5PTFWBTRMEymTmiaNZ/RA=</HostId></Error>
~~~

**Comment by lf-** [comment]
Oh, that's extremely interesting. So the repo used to be private, and maybe that's what happened?

**Comment by 1268** [comment]
probably - I bet the original URL work if you used your own authentication

**Comment by lf-** [comment]
Surprisingly not, it was also broken for me.

**Comment by 1268** [comment]
I would be careful using GitHub as free media hosting.

it could just be that they view that as abuse, and are purposefully killing the URL after a certain amount of time. not sure.
